#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true


bspc config normal_border_color "#1a1b26"
bspc config focused_border_color "#7aa2f7"

feh --bg-scale /home/silver/Wallpapers/cat.jpg 
picom -b -experimental-backends &
bash ~/launch.sh &
xsetroot -cursor_name left_ptr
